name: Test action
run-name: Name action ${{ github.actor }}

on: 
    pull_request: 
        branches: 
            - develop

jobs:
    name-pr:
        runs-on: ubuntu-latest
        name: Name job ${{ github.actor }} # name user
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                node-version: '20'
            - run: yarn --version
            - run: echo "action_ref = ${{ github.action_ref }}"
            - run: echo "action_path = ${{ github.action_path }}"
            - run: echo "action_repository = ${{ github.action_repository }}"
            - run: echo "action_status = ${{ github.action_status }}"
            - run: echo "actor_id = ${{ github.actor_id }}"
            - run: echo "base_ref = ${{ github.base_ref }}"
            - run: echo "event = ${{ github.event }}"
            - run: echo "event_name = ${{ github.event_name }}"
            - run: echo "event_path = ${{ github.event_path }}"
            - run: echo "path = ${{ github.path }}"
            - run: echo "ref = ${{ github.ref }}"
            - run: echo "workspace = ${{ github.workspace }}"
            - run: echo "workflow_ref = ${{ github.workflow_ref }}"
            - run: echo "ref_type = ${{ github.ref_type }}"
