name: Test action
run-name: Name action ${{ github.actor }}

on: 
    pull_request: 
        branches: 
            - develop

jobs:
    name-pr:
        runs-on: ubuntu-latest
        name: Name job ${{ github.actor }} # name user
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                node-version: '20'
            - run: yarn --version
            - run: echo "action_ref = ${{ github.action_ref }}" # работает только в env
            - run: echo "action_path = ${{ github.action_path }}"
            - run: echo "action_repository = ${{ github.action_repository }}"
            - run: echo "action_status = ${{ github.action_status }}"
            - run: echo "actor_id = ${{ github.actor_id }}"
            - run: echo "base_ref = ${{ github.base_ref }}"
            - run: echo "event = ${{ github.event }}"
            - run: echo "event_name = ${{ github.event_name }}"
            - run: echo "event_path = ${{ github.event_path }}"
            - run: echo "path = ${{ github.path }}"
            - run: echo "ref = ${{ github.ref }}"
            - run: echo "workspace = ${{ github.workspace }}"
            - run: echo "workflow_ref = ${{ github.workflow_ref }}"
            - run: echo "ref_type = ${{ github.ref_type }}"
            - run: echo "action = ${{ github.action }}"
    
    dump_contexts_to_log:
        runs-on: ubuntu-latest
        steps:
            - name: Dump GitHub context
              env:
                GITHUB_CONTEXT: ${{ toJson(github) }}
              run: echo "$GITHUB_CONTEXT"
            - name: Dump job context
              env:
                JOB_CONTEXT: ${{ toJson(job) }}
              run: echo "$JOB_CONTEXT"
            - name: Dump steps context
              env:
                STEPS_CONTEXT: ${{ toJson(steps) }}
              run: echo "$STEPS_CONTEXT"
            - name: Dump runner context
              env:
                RUNNER_CONTEXT: ${{ toJson(runner) }}
              run: echo "$RUNNER_CONTEXT"
            # - name: Dump strategy context
            #   env:
            #     STRATEGY_CONTEXT: ${{ toJson(strategy) }}
            #   run: echo "$STRATEGY_CONTEXT"
            # - name: Dump matrix context
            #   env:
            #     MATRIX_CONTEXT: ${{ toJson(matrix) }}
            #   run: echo "$MATRIX_CONTEXT"
