name: Test action
run-name: Name action ${{ github.actor }}

on: 
    pull_request: 
        branches: 
            - develop

jobs:
    name-pr:
        runs-on: ubuntu-latest
        name: Name job ${{ github.actor }} # name user
        steps:
            - uses: actions/checkout@v4
            - uses: actions/setup-node@v4
              with:
                node-version: '20'
            - run: yarn --version
            - run: echo "${{ github.action_ref }}"
            - run: echo "${{ github.action_path }}"
            - run: echo "${{ github.action_repository }}"
            - run: echo "${{ github.action_status }}"
            - run: echo "${{ github.actor_id }}"
            - run: echo "${{ github.base_ref }}"
            - run: echo "${{ github.event }}"
            - run: echo "${{ github.event_name }}"
            - run: echo "${{ github.event_path }}"
            - run: echo "${{ github.path }}"
            - run: echo "${{ github.ref }}"
            - run: echo "${{ github.workspace }}"
            - run: echo "${{ github.workflow_ref }}"
            - run: echo "${{ github.ref_type }}"
