name: Release

on:
  push:
    branches: [main, develop]

jobs:
  test-mode:
    - name: Action test
      uses: ./.github/workflow/test-pr.yaml
  
  patch:
    needs: test-mode
    if: ${{ github.event.ref == 'refs/head/develop' }}
    runs-on: ubuntu-latest

    steps:      
      - name: Current version
        id: get-current-version
        run: echo "Current version: $(cat package.json | jq -r .version)"

      - name: Create patch
        if: ${{ github.event.type == 'push' && github.event.ref == 'refs/heads/develop' }}
        run: /
          npx --quiet semver bump patch package.json
          git add package.json
          git commit -m "Bump patch"
