name: Yml 1
run-name: Release

on: 
  push: 
    branches: [main]

permissions: 
  contents: read

jobs:
  run-job:
    name: Job 1
    runs-on: ubuntu-latest
    permissions: 
      contents: write
      issues: write
      id-token: write
      pull-requests: write
    steps:
      - name: j1
        run: echo '${{ toJson(runner) }}'
      - name: Load repo
        uses: actions/checkout@v4
        with:
          fetch-depth: 0
          token: ${{ secrets.GH_AUTH_TOKEN }}
      - uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
          cache-dependency-path: 'yarn.lock'
      - name: install
        run: yarn
      - name: Create build
        run: yarn build
      - uses: actions/upload-artifact@v4
        with:
          path: build
      - name: Ls
        run: ls
      - name: Tag version
        id: tag-bump
        run: |
          git config --global user.name "github-actions[bot]"
          git config --global user.email "github-actions[bot]@users.noreply.github.com"
          yarn version --patch -m "chore(release): %s"
          VERSION=$(node -p "require('./package.json').version")
          echo "VERSION=$VERSION" >> $GITHUB_ENV
          git push --follow-tags [skip ci]
      
      - name: Create release
        uses: actions/create-release@v1
        id: create_release
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        with:
          tag_name: ${{env.VERSION}}
          release_name: Release ${{env.VERSION}}
          draft: false
          prerelease: false

      - name: Upload build artifact to release
        uses: actions/upload-release-asset@v1
        with:
          upload_url: ${{ steps.create_release.outputs.upload_url }}
          asset_path: ./build
          asset_name: build-artifact.zip
          asset_content_type: application/zip

      