name: release

on: [push]

jobs:
    release:
        runs-on: ubuntu-latest
        steps:
            - name: List files
              run: ls
            - name: Checkout code
              uses: actions/checkout@v4
            - name: List after
              run: ls