name: CI/CD

on:
  pull_request:
    branches:
      - develop

jobs:
  test:
    name: Run tests on Node.js v20
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v4
      - name: Use Node.js v20
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'yarn'
          cache-dependency-path: yarn.lock

      - name: Install dependencies
        run: npm install
      - name: Run tests
        run: npm test

  merge-to-main:
    name: Merge to main and create version tag
    runs-on: ubuntu-latest
    needs: test
    if: github.event_name == 'pull_request' && github.event.action == 'closed' && github.event.pull_request.merged == true && github.ref == 'refs/heads/develop'
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Merge changes into main
        run: git fetch && git checkout main && git merge --no-ff ${{ github.event.pull_request.head.sha }} --no-edit && git push origin main
      - name: Create version tag
        run: |
          git tag -a v$(npm version patch) -m "Version $(npm version patch)"
          git push origin --tags
